install:
 # tex install
 - source ./.ci-support/install_tex_packages.sh
 - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - export PATH="$HOME/miniconda/bin:$PATH"
 - bash miniconda.sh -b -p $HOME/miniconda
 - conda config --set always_yes yes --set changeps1 no
 - conda install -c conda-forge pygments
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
 - cd source
 - pdflatex -shell-escape thesis.tex
 - bibtex thesis
 - pdflatex -shell-escape thesis.tex
 - pdflatex -shell-escape thesis.tex
 - cp *.pdf ../.
 - cd ../
